# Conférences Python Master TIDE #1

## Librairie pandas

Dataset des communes françaises : `correspondance-code-insee-code-postal.csv`

0) Import
- Importer la librairie pandas
- Utiliser l'option suivante
```python
pd.set_option("display.min_rows", 16)
```

1) Ecrire une fonction qui charge le fichier CSV
- Uniquement les 11 premières colonnes
- Utiliser la colonne "Code INSEE" comme index
- Trier selon l'index
- Pour vérifier, exécuter les tests unitaires

```python
def lecture_geo():
    pass
```

2) Questions
- Combien y a-t-il de départements ?
- Quelle commune est la plus haute ?
- Quelle commune est la plus peuplée ?
- Quelle commune a le nom le plus court ?
- Quelle commune a le nom le plus long ?
- Quel est le nom de commune le plus fréquent ?
- Ecrire une fonction qui recherche les communes se terminant par un motif du type "-mot1-mot2" (par exemple "-SUR-MER")
```python
def selection(mot1, mot2):
    pass
```
- Quelles villes contiennent deux "Z" (accolés, séparés par une seule lettre, séparés par un nombre quelconque de lettres, séparés par au moins une lettre) ?
- Quelles sont les dix terminaisons des noms de communes du type "-mot1-mot2" les plus fréquentes ?

3) Transformations
- Passer la colonne "Superficie" en km²
- Passer la colonne "Altitude Moyenne" en entiers
- Modifier la colonne "Statut" en categorie ordonnée

4) Géographie
- Créer une colonne "CP Ville" à partir du code postal et du nom de chaque commune
- Extraire la latitude et la longitude de la colonne "geo_point_2d"
- Ecrire une fonction qui retourne le "CP Ville" de la commune la plus proche d'une latitude et d'une longitude
```python
def ville(lat, long):
    pass
```
- Ecrire une fonction qui transforme des coordonnées GPS (en degrés, minutes et secondes) en coordonnées décimales
```python
def gps2dec(deg, mn, sec):
    pass
```
- Choisir une petite commune française sur Wikipédia et vérifier qu'elle est trouvée à partir de ces coordonnnées GPS en utilisant les 2 fonctions définies

5) Géométrie
- Décoder les données JSON de la colonne "geo_shape"
- Donner le décompte des différentes valeurs associées à la clé "type"
- Donner le décompte des longueurs des listes associées à la clé "coordinates"
- Quelles sont les "CP Ville" des communes de type "Polygon" et dont la longueur des listes accédées avec la clé "coordinates" vaut 2 ?

6) Graphiques
- Afficher un histogramme avec les longueurs des noms des communes
- Afficher un graphique de type scatterplot à partir des coordonnées des communes
- Trouver une condition pour limiter le dataset à la France métropolitaine et afficher un graphique
- Mettre toutes les communes à moins de 1000m en bleu et celle à plus de 1000m en rouge
- Afficher un graphique de type scatterplot dans lequel les communes se terminant par un motif du type "-mot1-mot2" sont mis dans une autre couleur
- Afficher un graphique de type scatterplot dans lequel la couleur utilisée dépend de la colonne "Altitude moyenne" selon la colormap "Spectral_r"
- Afficher une carte de France métropolitaine avec les préfectures de région et leur nom, en corrigeant celles qui sont des arrondissements de Paris, Lyon ou Marseille.

&copy; Francis Wolinski 2024

In [2]:
import pandas as pd

In [ ]:
def lecture_geo():
    df = pd.read_csv("data/correspondance-code-insee-code-postal.csv",
                     sep=";",
                     index_col="Code INSEE",
                     usecols=range(11)
                    )
    df = df.sort_index()
    return df

In [3]:
def lecture_geo():
    df = (pd.read_csv("data/correspondance-code-insee-code-postal.csv",
                     sep=";",
                     index_col="Code INSEE",
                     usecols=range(11)
                    )
          .sort_index()
         )
    return df

In [8]:
df = lecture_geo()

In [9]:
df.info()

<class 'pandas.core.frame.DataFrame'>
Index: 36742 entries, 01001 to 97617
Data columns (total 10 columns):
 #   Column            Non-Null Count  Dtype
---  ------            --------------  -----
 0   Code Postal       36742 non-null  object
 1   Commune           36742 non-null  object
 2   Département       36742 non-null  object
 3   Région            36742 non-null  object
 4   Statut            36742 non-null  object
 5   Altitude Moyenne  36742 non-null  float64
 6   Superficie        36742 non-null  float64
 7   Population        36742 non-null  float64
 8   geo_point_2d      36742 non-null  object
 9   geo_shape         36742 non-null  object
dtypes: float64(3), object(7)
memory usage: 3.1+ MB

In [11]:
df["Département"].nunique()

101

In [12]:
df.nunique()

Code Postal          6101
Commune             34130
Département           101
Région                 27
Statut                  6
Altitude Moyenne     1652
Superficie           5246
Population            509
geo_point_2d        36742
geo_shape           36742
dtype: int64

In [15]:
df.loc[df["Altitude Moyenne"]==df["Altitude Moyenne"].max(), "Commune"]

Code INSEE
73047    BONNEVAL-SUR-ARC
Name: Commune, dtype: object

In [16]:
df.loc[df["Altitude Moyenne"].idxmax(), "Commune"]

'BONNEVAL-SUR-ARC'

In [17]:
df.loc[df["Population"].idxmax(), "Commune"]

'TOULOUSE'

In [21]:
df.loc[df["Commune"].str.len().idxmin(), "Commune"]

'Y'

In [22]:
df.loc[df["Commune"].str.len().idxmax(), "Commune"]

'SAINT-REMY-EN-BOUZEMONT-SAINT-GENEST-ET-ISSON'

In [27]:
df["Commune"].value_counts().index[0]

'SAINTE-COLOMBE'

In [28]:
%timeit df["Commune"].value_counts().index[0]

6.13 ms ± 432 μs per loop (mean ± std. dev. of 7 runs, 100 loops each)

In [30]:
%timeit df["Commune"].value_counts().idxmax()

6.32 ms ± 736 μs per loop (mean ± std. dev. of 7 runs, 100 loops each)

In [33]:
def selection(mot1, mot2):
    pattern = f"-{mot1}-{mot2}"
    selection = df.loc[df["Commune"].str.endswith(pattern)]
    return selection

In [34]:
selection("SUR", "MER")

,Code Postal,Commune,Département,Région,Statut,Altitude Moyenne,Superficie,Population,geo_point_2d,geo_shape
Code INSEE,,,,,,,,,,
06011,06310,BEAULIEU-SUR-MER,ALPES-MARITIMES,PROVENCE-ALPES-COTE D'AZUR,Commune simple,36.0,108.0,3.7,"43.7079039397, 7.33256934881","{""type"": ""Polygon"", ""coordinates"": [[[7.326789..."
06027,06800,CAGNES-SUR-MER,ALPES-MARITIMES,PROVENCE-ALPES-COTE D'AZUR,Chef-lieu canton,64.0,1821.0,48.0,"43.6715162078, 7.15275703379","{""type"": ""Polygon"", ""coordinates"": [[[7.145493..."
06138,06590,THEOULE-SUR-MER,ALPES-MARITIMES,PROVENCE-ALPES-COTE D'AZUR,Commune simple,130.0,1072.0,1.6,"43.4985345439, 6.92965248383","{""type"": ""Polygon"", ""coordinates"": [[[6.933726..."
06159,06230,VILLEFRANCHE-SUR-MER,ALPES-MARITIMES,PROVENCE-ALPES-COTE D'AZUR,Chef-lieu canton,231.0,492.0,5.8,"43.7122153121, 7.32225410533","{""type"": ""Polygon"", ""coordinates"": [[[7.308745..."
13039,13270,FOS-SUR-MER,BOUCHES-DU-RHONE,PROVENCE-ALPES-COTE D'AZUR,Commune simple,5.0,8868.0,15.5,"43.4556812107, 4.90452133912","{""type"": ""Polygon"", ""coordinates"": [[[4.972215..."
...,...,...,...,...,...,...,...,...,...,...
85166,85340,OLONNE-SUR-MER,VENDEE,PAYS DE LA LOIRE,Commune simple,12.0,4608.0,13.3,"46.5413300559, -1.78813984621","{""type"": ""Polygon"", ""coordinates"": [[[-1.77321..."
85201,85540,SAINT-BENOIST-SUR-MER,VENDEE,PAYS DE LA LOIRE,Commune simple,9.0,1556.0,0.3,"46.4266286403, -1.3399129604","{""type"": ""Polygon"", ""coordinates"": [[[-1.31773..."
85243,85470,BREM-SUR-MER,VENDEE,PAYS DE LA LOIRE,Commune simple,27.0,1616.0,2.6,"46.6118566989, -1.81003917923","{""type"": ""Polygon"", ""coordinates"": [[[-1.81551..."
85294,85360,LA TRANCHE-SUR-MER,VENDEE,PAYS DE LA LOIRE,Commune simple,5.0,2103.0,2.7,"46.3564601605, -1.43136322126","{""type"": ""Polygon"", ""coordinates"": [[[-1.35516..."
85307,85460,LA FAUTE-SUR-MER,VENDEE,PAYS DE LA LOIRE,Commune simple,4.0,726.0,0.9,"46.3199919131, -1.31487049579","{""type"": ""Polygon"", ""coordinates"": [[[-1.30340..."

In [39]:
df.loc[df["Commune"].str.contains("ZZ"), "Commune"]

Code INSEE
2A027              AZZANA
2A099             COZZANO
2A118             FOZZANO
2A259               REZZA
2A336    VALLE-DI-MEZZANA
2B143        LINGUIZZETTA
2B147               LOZZI
2B149       LUGO-DI-NAZZA
2B157             MAZZOLA
2B164    MONACIA-D'OREZZA
2B216            PIAZZALI
2B217            PIAZZOLE
2B222        PIE-D'OREZZA
2B236     POGGIO-DI-NAZZA
2B242      POGGIO-MEZZANA
2B291            STAZZONA
2B338      VALLE-D'OREZZA
2B347             VEZZANI
68030       BERGHOLTZZELL
Name: Commune, dtype: object

In [38]:
df.loc[df["Commune"].str.contains("Z.Z"), "Commune"]

Code INSEE
2A363                   ZOZA
43261               VEZEZOUX
71174    DEZIZE-LES-MARANGES
Name: Commune, dtype: object

In [40]:
df.loc[df["Commune"].str.contains("Z.*Z"), "Commune"]

Code INSEE
07161    MONTPEZAT-SOUS-BAUZON
09105       DAUMAZAN-SUR-ARIZE
09167           LEZAT-SUR-LEZE
11034         BELVEZE-DU-RAZES
11228      MAZEROLLES-DU-RAZES
                 ...
74311           VIUZ-EN-SALLAZ
78337            LIMETZ-VILLEZ
88404      ROZIERES-SUR-MOUZON
95282               GOUZANGREZ
97608                 DZAOUDZI
Name: Commune, Length: 67, dtype: object

In [41]:
df.loc[df["Commune"].str.contains("Z.+Z"), "Commune"]

Code INSEE
07161       MONTPEZAT-SOUS-BAUZON
09105          DAUMAZAN-SUR-ARIZE
09167              LEZAT-SUR-LEZE
11034            BELVEZE-DU-RAZES
11228         MAZEROLLES-DU-RAZES
11417          VILLARZEL-DU-RAZES
12294           VEZINS-DE-LEVEZOU
16378                 TAIZE-AIZIE
29008            BEUZEC-CAP-SIZUN
29176             PLONEVEZ-PORZAY
2A026              AZILONE-AMPAZA
2A362                       ZONZA
2A363                        ZOZA
31245               JUZET-D'IZAUT
34069         CAZOULS-LES-BEZIERS
34279    SAINT-NAZAIRE-DE-LADAREZ
34280      SAINT-NAZAIRE-DE-PEZAN
34310          THEZAN-LES-BEZIERS
42193             ROZIER-EN-DONZY
43131             MAZERAT-AUROUZE
43261                    VEZEZOUX
45026        BAZOCHES-SUR-LE-BETZ
45204          MEZIERES-LEZ-CLERY
45245          OUZOUER-SUR-TREZEE
47006          ALLEZ-ET-CAZENEUVE
54129           CIREY-SUR-VEZOUZE
54161         DOMEVRE-SUR-VEZOUZE
55024      AZANNES-ET-SOUMAZANNES
55178          ERIZE-SAINT-DIZIER
56090           INZINZAC-LOCHRIST
57433          MAIZIERES-LES-METZ
58116                   FLEZ-CUZY
59667                  ZERMEZEELE
63435           TOURZEL-RONZIERES
64063           ARZACQ-ARRAZIGUET
64373              MAZERES-LEZONS
65020           ARCIZAC-EZ-ANGLES
65203               GEZ-EZ-ANGLES
67347       OBERMODERN-ZUTZENDORF
69052           CHAZAY-D'AZERGUES
69229     SAINT-NIZIER-D'AZERGUES
71174         DEZIZE-LES-MARANGES
74310             VIUZ-LA-CHIESAZ
74311              VIUZ-EN-SALLAZ
78337               LIMETZ-VILLEZ
88404         ROZIERES-SUR-MOUZON
95282                  GOUZANGREZ
97608                    DZAOUDZI
Name: Commune, dtype: object

In [45]:
df["Commune"].str.extract("(-.+-.+)$", expand=False).value_counts().head(10)

Commune
-SUR-MER         88
-SUR-SEINE       67
-SUR-MARNE       55
-LES-BAINS       53
-LE-CHATEAU      52
-SUR-LOIRE       52
-LE-SEC          45
-LE-GRAND        43
-SUR-MEUSE       42
-SAINT-MARTIN    41
Name: count, dtype: int64

In [46]:
df["Commune"].str.extract("-(.+)-(.+)$")

              0       1
Code INSEE
01001       NaN     NaN
01002        DE   VAREY
01004        EN   BUGEY
01005        EN  DOMBES
01006       NaN     NaN
...         ...     ...
97613       NaN     NaN
97614       NaN     NaN
97615       NaN     NaN
97616       NaN     NaN
97617       NaN     NaN

[36742 rows x 2 columns]

In [51]:
df["Superficie"] /= 100

In [52]:
df["Superficie"]

Code INSEE
01001    15.65
01002     9.12
01004    24.48
01005    16.05
01006     6.02
         ...
97613    21.55
97614    18.28
97615     4.26
97616    10.85
97617    34.26
Name: Superficie, Length: 36742, dtype: float64

In [54]:
df["Altitude Moyenne"] = df["Altitude Moyenne"].astype(int)
df["Altitude Moyenne"]

Code INSEE
01001    242
01002    483
01004    379
01005    290
01006    589
        ...
97613     96
97614    175
97615     52
97616    130
97617    147
Name: Altitude Moyenne, Length: 36742, dtype: int64

In [56]:
df["Statut"].unique()

array(['Commune simple', 'Chef-lieu canton', 'Sous-préfecture',
       'Préfecture', 'Préfecture de région', "Capitale d'état"],
      dtype=object)

In [57]:
%timeit df.loc[df["Statut"] == 'Commune simple']

8.79 ms ± 435 μs per loop (mean ± std. dev. of 7 runs, 100 loops each)

In [58]:
df.info()

<class 'pandas.core.frame.DataFrame'>
Index: 36742 entries, 01001 to 97617
Data columns (total 10 columns):
 #   Column            Non-Null Count  Dtype
---  ------            --------------  -----
 0   Code Postal       36742 non-null  object
 1   Commune           36742 non-null  object
 2   Département       36742 non-null  object
 3   Région            36742 non-null  object
 4   Statut            36742 non-null  object
 5   Altitude Moyenne  36742 non-null  int64
 6   Superficie        36742 non-null  float64
 7   Population        36742 non-null  float64
 8   geo_point_2d      36742 non-null  object
 9   geo_shape         36742 non-null  object
dtypes: float64(2), int64(1), object(7)
memory usage: 4.1+ MB

In [59]:
statut_cat = pd.CategoricalDtype(categories=['Commune simple', 'Chef-lieu canton', 'Sous-préfecture',
                                             'Préfecture', 'Préfecture de région', "Capitale d'état"],
                                 ordered=True)
df["Statut"] = df["Statut"].astype(statut_cat)
df.info()

<class 'pandas.core.frame.DataFrame'>
Index: 36742 entries, 01001 to 97617
Data columns (total 10 columns):
 #   Column            Non-Null Count  Dtype
---  ------            --------------  -----
 0   Code Postal       36742 non-null  object
 1   Commune           36742 non-null  object
 2   Département       36742 non-null  object
 3   Région            36742 non-null  object
 4   Statut            36742 non-null  category
 5   Altitude Moyenne  36742 non-null  int64
 6   Superficie        36742 non-null  float64
 7   Population        36742 non-null  float64
 8   geo_point_2d      36742 non-null  object
 9   geo_shape         36742 non-null  object
dtypes: category(1), float64(2), int64(1), object(6)
memory usage: 3.8+ MB

In [62]:
df["Statut"].cat.codes

Code INSEE
01001    0
01002    0
01004    1
01005    0
01006    0
        ..
97613    1
97614    1
97615    1
97616    1
97617    1
Length: 36742, dtype: int8

In [63]:
%timeit df.loc[df["Statut"] == 'Commune simple']

5.96 ms ± 102 μs per loop (mean ± std. dev. of 7 runs, 100 loops each)

In [65]:
var = df.loc[df["Commune"].str.startswith("A")]
var["Population"] = var["Population"].astype(int)

/tmp/ipykernel_5036/3093096956.py:2: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  var["Population"] = var["Population"].astype(int)

In [66]:
df["CP Ville"] = df["Code Postal"] + " " + df["Commune"]
df

,Code Postal,Commune,Département,Région,Statut,Altitude Moyenne,Superficie,Population,geo_point_2d,geo_shape,CP Ville
Code INSEE,,,,,,,,,,,
01001,01400,L'ABERGEMENT-CLEMENCIAT,AIN,RHONE-ALPES,Commune simple,242,15.65,0.8,"46.1534255214, 4.92611354223","{""type"": ""Polygon"", ""coordinates"": [[[4.926273...",01400 L'ABERGEMENT-CLEMENCIAT
01002,01640,L'ABERGEMENT-DE-VAREY,AIN,RHONE-ALPES,Commune simple,483,9.12,0.2,"46.0091878776, 5.42801696363","{""type"": ""Polygon"", ""coordinates"": [[[5.430089...",01640 L'ABERGEMENT-DE-VAREY
01004,01500,AMBERIEU-EN-BUGEY,AIN,RHONE-ALPES,Chef-lieu canton,379,24.48,13.4,"45.9608475114, 5.3729257777","{""type"": ""Polygon"", ""coordinates"": [[[5.386190...",01500 AMBERIEU-EN-BUGEY
01005,01330,AMBERIEUX-EN-DOMBES,AIN,RHONE-ALPES,Commune simple,290,16.05,1.6,"45.9961799872, 4.91227250796","{""type"": ""Polygon"", ""coordinates"": [[[4.895580...",01330 AMBERIEUX-EN-DOMBES
01006,01300,AMBLEON,AIN,RHONE-ALPES,Commune simple,589,6.02,0.1,"45.7494989044, 5.59432017366","{""type"": ""Polygon"", ""coordinates"": [[[5.614854...",01300 AMBLEON
...,...,...,...,...,...,...,...,...,...,...,...
97613,97650,M'TSANGAMOUJI,MAYOTTE,MAYOTTE,Chef-lieu canton,96,21.55,5.0,"-12.7513099309, 45.0871696871","{""type"": ""Polygon"", ""coordinates"": [[[45.10168...",97650 M'TSANGAMOUJI
97614,97670,OUANGANI,MAYOTTE,MAYOTTE,Chef-lieu canton,175,18.28,6.6,"-12.8370955196, 45.1379095497","{""type"": ""Polygon"", ""coordinates"": [[[45.15401...",97670 OUANGANI
97615,97610,PAMANDZI,MAYOTTE,MAYOTTE,Chef-lieu canton,52,4.26,9.1,"-12.7961353309, 45.2842063102","{""type"": ""Polygon"", ""coordinates"": [[[45.29645...",97610 PAMANDZI
97616,97640,SADA,MAYOTTE,MAYOTTE,Chef-lieu canton,130,10.85,8.0,"-12.8611649609, 45.1185503145","{""type"": ""Polygon"", ""coordinates"": [[[45.13226...",97640 SADA
97617,97680,TSINGONI,MAYOTTE,MAYOTTE,Chef-lieu canton,147,34.26,9.2,"-12.7821666736, 45.1344279083","{""type"": ""Polygon"", ""coordinates"": [[[45.15256...",97680 TSINGONI

In [70]:
type(df["geo_point_2d"].iloc[0])

str

In [75]:
float(df["geo_point_2d"].iloc[0].split(', ')[0])

46.1534255214

In [77]:
df["geo_point_2d"].apply(lambda x: float(x.split(', ')[0]))

Code INSEE
01001    46.153426
01002    46.009188
01004    45.960848
01005    45.996180
01006    45.749499
           ...
97613   -12.751310
97614   -12.837096
97615   -12.796135
97616   -12.861165
97617   -12.782167
Name: geo_point_2d, Length: 36742, dtype: float64

In [78]:
df["geo_point_2d"].apply(lambda x: float(x.split(', ')[1]))

Code INSEE
01001     4.926114
01002     5.428017
01004     5.372926
01005     4.912273
01006     5.594320
           ...
97613    45.087170
97614    45.137910
97615    45.284206
97616    45.118550
97617    45.134428
Name: geo_point_2d, Length: 36742, dtype: float64

In [81]:
df[["Latitude", "Longitude"]] = df["geo_point_2d"].str.extract("(.+), (.+)").astype(float)
df.info()

<class 'pandas.core.frame.DataFrame'>
Index: 36742 entries, 01001 to 97617
Data columns (total 13 columns):
 #   Column            Non-Null Count  Dtype
---  ------            --------------  -----
 0   Code Postal       36742 non-null  object
 1   Commune           36742 non-null  object
 2   Département       36742 non-null  object
 3   Région            36742 non-null  object
 4   Statut            36742 non-null  category
 5   Altitude Moyenne  36742 non-null  int64
 6   Superficie        36742 non-null  float64
 7   Population        36742 non-null  float64
 8   geo_point_2d      36742 non-null  object
 9   geo_shape         36742 non-null  object
 10  CP Ville          36742 non-null  object
 11  Latitude          36742 non-null  float64
 12  Longitude         36742 non-null  float64
dtypes: category(1), float64(4), int64(1), object(7)
memory usage: 4.7+ MB

In [82]:
df

,Code Postal,Commune,Département,Région,Statut,Altitude Moyenne,Superficie,Population,geo_point_2d,geo_shape,CP Ville,Latitude,Longitude
Code INSEE,,,,,,,,,,,,,
01001,01400,L'ABERGEMENT-CLEMENCIAT,AIN,RHONE-ALPES,Commune simple,242,15.65,0.8,"46.1534255214, 4.92611354223","{""type"": ""Polygon"", ""coordinates"": [[[4.926273...",01400 L'ABERGEMENT-CLEMENCIAT,46.153426,4.926114
01002,01640,L'ABERGEMENT-DE-VAREY,AIN,RHONE-ALPES,Commune simple,483,9.12,0.2,"46.0091878776, 5.42801696363","{""type"": ""Polygon"", ""coordinates"": [[[5.430089...",01640 L'ABERGEMENT-DE-VAREY,46.009188,5.428017
01004,01500,AMBERIEU-EN-BUGEY,AIN,RHONE-ALPES,Chef-lieu canton,379,24.48,13.4,"45.9608475114, 5.3729257777","{""type"": ""Polygon"", ""coordinates"": [[[5.386190...",01500 AMBERIEU-EN-BUGEY,45.960848,5.372926
01005,01330,AMBERIEUX-EN-DOMBES,AIN,RHONE-ALPES,Commune simple,290,16.05,1.6,"45.9961799872, 4.91227250796","{""type"": ""Polygon"", ""coordinates"": [[[4.895580...",01330 AMBERIEUX-EN-DOMBES,45.996180,4.912273
01006,01300,AMBLEON,AIN,RHONE-ALPES,Commune simple,589,6.02,0.1,"45.7494989044, 5.59432017366","{""type"": ""Polygon"", ""coordinates"": [[[5.614854...",01300 AMBLEON,45.749499,5.594320
...,...,...,...,...,...,...,...,...,...,...,...,...,...
97613,97650,M'TSANGAMOUJI,MAYOTTE,MAYOTTE,Chef-lieu canton,96,21.55,5.0,"-12.7513099309, 45.0871696871","{""type"": ""Polygon"", ""coordinates"": [[[45.10168...",97650 M'TSANGAMOUJI,-12.751310,45.087170
97614,97670,OUANGANI,MAYOTTE,MAYOTTE,Chef-lieu canton,175,18.28,6.6,"-12.8370955196, 45.1379095497","{""type"": ""Polygon"", ""coordinates"": [[[45.15401...",97670 OUANGANI,-12.837096,45.137910
97615,97610,PAMANDZI,MAYOTTE,MAYOTTE,Chef-lieu canton,52,4.26,9.1,"-12.7961353309, 45.2842063102","{""type"": ""Polygon"", ""coordinates"": [[[45.29645...",97610 PAMANDZI,-12.796135,45.284206
97616,97640,SADA,MAYOTTE,MAYOTTE,Chef-lieu canton,130,10.85,8.0,"-12.8611649609, 45.1185503145","{""type"": ""Polygon"", ""coordinates"": [[[45.13226...",97640 SADA,-12.861165,45.118550
97617,97680,TSINGONI,MAYOTTE,MAYOTTE,Chef-lieu canton,147,34.26,9.2,"-12.7821666736, 45.1344279083","{""type"": ""Polygon"", ""coordinates"": [[[45.15256...",97680 TSINGONI,-12.782167,45.134428

In [87]:
import numpy as np

def ville(lat, long):
    dist = np.sqrt((df["Latitude"]-lat)**2 + (df["Longitude"]-long)**2)
    return df.loc[dist.idxmin(), "CP Ville"]

In [91]:
def ville2(lat, long):
    dist2 = (df["Latitude"]-lat)**2 + (df["Longitude"]-long)**2
    return df.loc[dist2.idxmin(), "CP Ville"]

In [85]:
def gps2dec(deg, mn, sec):
    return deg + mn / 60 + sec / 3600

In [88]:
# 49° 02′ 12″ nord, 7° 41′ 18″ est
ville(gps2dec(49, 2, 12), gps2dec(7, 41, 18))

'67510 OBERSTEINBACH'

In [92]:
# 48° 40′ 07″ nord, 3° 54′ 45″ ouest

ville2(gps2dec(48, 40, 7), -gps2dec(3, 54, 45))

'29660 CARANTEC'

### Tests

In [5]:
# tests unitaires de la fonction lecture_geo

import unittest

class Session1Test(unittest.TestCase):
    """
    Tests unitaires du chargement du fichier :
    correspondance-code-insee-code-postal.csv
    """
        
    def test_1_dataframe(self):
        df = lecture_geo()
        self.assertTrue(isinstance(df, pd.DataFrame))
        
    def test_2_columns(self):
        df = lecture_geo()
        self.assertEqual(len(df.columns), 10)
        
    def test_3_index(self):
        df = lecture_geo()
        self.assertTrue(isinstance(df.index, pd.Index))
        
    def test_4_index_name(self):
        df = lecture_geo()
        self.assertEqual(df.index.name, "Code INSEE")
        
    def test_5_index_sort(self):
        df = lecture_geo()
        self.assertEqual(df.index.min(), df.index[0])
        self.assertEqual(df.index.max(), df.index[-1])

In [6]:
# fonction run_tests
def run_tests():
    test_suite = unittest.TestLoader().loadTestsFromTestCase(Session1Test)
    runner = unittest.TextTestRunner(verbosity=2)
    runner.run(test_suite)

In [7]:
# run tests
run_tests()

test_1_dataframe (__main__.Session1Test.test_1_dataframe) ... ok
test_2_columns (__main__.Session1Test.test_2_columns) ... ok
test_3_index (__main__.Session1Test.test_3_index) ... ok
test_4_index_name (__main__.Session1Test.test_4_index_name) ... ok
test_5_index_sort (__main__.Session1Test.test_5_index_sort) ... ok

----------------------------------------------------------------------
Ran 5 tests in 1.486s

OK