# Conférences Python Master TIDE #3

## A) Taux de change

On va s'intéresser au dataset des cours des devises de la Banque de France :
- https://webstat.banque-france.fr/fr/#/node/5385566

Les données sont dans le fichier `Webstat_Export.csv`.

L'idée est de charger les données, de les nettoyer et de pouvoir accéder aux cours de certaines devises à partir de leur code ISO3. On retiendra uniquement les colonnes se terminant effectivement par un code ISO3 entre parenthèses. Par ex., "Dollar des Etats-Unis (USD)".

1) Charger le fichier dans un DataFrame dont l'index doit correspondre aux dates, triées dans l'ordre chronologique et les colonnes doivent être les codes ISO3 des devises.

2) Sélectionner les devises : ['USD', 'CHF', 'GBP', 'JPY', 'TRY', 'CNY']

3) Calculer la moyenne des taux de change par année. Voir les codes de resampling : https://pandas.pydata.org/pandas-docs/stable/user_guide/timeseries.html#dateoffset-objects

4) Faire des graphiques avec :
- Les taux de change divisés par leur moyenne.
- Les taux de change divisés par leur moyenne avec une moyenne glissante de 30 jours ou bien un maximum glissant de 100 jours.
- Les taux de change divisés par la dernière valeur connue avec une moyenne glissante de 30 jours.

5) Réindexer le DataFrame en prenant toutes les dates et compléter les valeurs manquantes par interpolation linéaire.

6) Avec la librairie **sparklines** afficher un DataFrame avec la moyenne annuelle des taux de change pour une monnaie donnée ainsi que la tendance par trimestre.

```python
import sparklines

print(sparklines.sparklines(pd.Series(range(8)))[0])
```

## B) Données télécom

Dataset des opérateurs télécom : `couverture-2g-3g-4g-en-france-par-operateur-juillet-2015.csv`

1) Chargez le fichier dans un DataFrame.

2) Transformez ce DataFrame large en un DataFrame long en isolant les colonnes d'identification d'une part et les colonnes de valeurs de couverture d'autre part.

3) Rajoutez 3 colonnes "Opérateur", "Type Couverture" et "Réseau" calculées à partir de la colonne "variable" obtenue en 2.

4) Chargez le DataFrame des communes déjà utilisé et effectuez une jointure sur le code INSEE.

6) Pour le réseau 4G et la couverture surfacique, calculez la moyenne des couvertures par statut de commune et par opérateur. Pour quel couple (statut, opérateur) a-t-on la moyenne de la couverture la plus faible ?

## C) Données RH

Dataset de StackOverflow : `survey_results_public_2022.zip`

1) Charger le fichier dans un DataFrame.

2) Sélectionner une colonne se terminant par "HaveWorkedWith" ou "WantToWorkWith" et la transformer en données numériques 0 ou 1 en utilisant la méthode `get_dummies()` de **pandas**.

3) Calculer un score en sommant les valeurs de chaque participant et afficher un diagramme de type box.

4) Considérer les colonnes "Age", "MainBranch" et "RemoteWork". En utilisant la classe `OneHotEncoder` de la librairie **scikit-learn** transformer ces colonnes en données numériques.


&copy; Francis Wolinski 2024

In [16]:
import numpy as np
import pandas as pd

In [65]:
df = pd.read_csv("data/Webstat_Export.csv",
                 sep=";",
                 skiprows=[1, 2],
                 na_values="-",
                 keep_default_na=False,
                 decimal=","
                )
df

/tmp/ipykernel_8727/1811105670.py:1: DtypeWarning: Columns (3,4,5,6,7,8,10,11,14,15,17,18,19,20,21,22,23,27,28,29,30,31,32,33,35,36,39,40,41,43) have mixed types. Specify dtype option on import or set low_memory=False.
  df = pd.read_csv("data/Webstat_Export.csv",

,Titre :,"Taux de change effectif réel - 36 partenaires commerciaux, variation sur 3 ans",Taux de change effectif réel - 16 partenaires commerciaux (zone euro),Dollar australien (AUD),Lev bulgare (BGN),Real brésilien (BRL),Dollar canadien (CAD),Franc suisse (CHF),Yuan renminbi chinois (CNY),Livre chypriote (CYP),...,Dollar de Singapour (SGD).1,Cours de change de l'euro contre dollar de Singapour (SGD) - fin de mois,Baht thaïlandais (THB).1,Cours de change de l'euro contre baht thaïlandais (THB) - fin de mois,Livre turque (TRY).1,Cours de change de l'euro contre nouvelle livre turque (TRY) - fin de mois,Dollar des Etats-Unis (USD).1,Cours de change de l'euro contre dollar des Etats-Unis (USD) - fin de mois,Rand sud-africain (ZAR).1,Cours de change de l'euro contre rand sud-africain (ZAR) - fin de mois
0,15/05/2024,,,1.6308,1.9558,5.5827,1.4763,0.98,7.8212,,...,,,,,,,,,,
1,14/05/2024,,,1.6329,1.9558,5.5419,1.4753,0.9801,7.8103,,...,,,,,,,,,,
2,13/05/2024,,,1.6305,1.9558,5.5486,1.4757,0.9784,7.8095,,...,,,,,,,,,,
3,12/05/2024,,,NaN,NaN,NaN,NaN,NaN,NaN,,...,,,,,,,,,,
4,11/05/2024,,,NaN,NaN,NaN,NaN,NaN,NaN,,...,,,,,,,,,,
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
9260,07/01/1999,,,"1,8474",,,"1,7602","1,6165",,"0,58187",...,,,,,,,,,,
9261,06/01/1999,,,"1,882",,,"1,7711","1,6116",,"0,582",...,,,,,,,,,,
9262,05/01/1999,,,"1,8944",,,"1,7965","1,6123",,"0,5823",...,,,,,,,,,,
9263,04/01/1999,,,"1,91",,,"1,8004","1,6168",,"0,58231",...,,,,,,,,,,
9264,01/01/1999,,,,,,,,,,...,"1,9496","1,9233","42,497","42,0319","0,3765","0,3779","1,1608","1,1384","6,9572","6,8804"

In [66]:
cols = pd.Series(df.columns).str.extract(r"\(([A-Z]{3})\)$", expand=False).values.tolist()
cols[0] = "date"
df.columns = cols
df = df.drop(np.nan, axis=1)
df

,date,AUD,BGN,BRL,CAD,CHF,CNY,CYP,CZK,DKK,...,RON,RUB,SEK,SGD,SIT,SKK,THB,TRY,USD,ZAR
0,15/05/2024,1.6308,1.9558,5.5827,1.4763,0.98,7.8212,,24.766,7.4617,...,4.9758,,11.6751,1.4609,,,39.58,34.9765,1.0832,19.9073
1,14/05/2024,1.6329,1.9558,5.5419,1.4753,0.9801,7.8103,,24.75,7.4608,...,4.9758,,11.7285,1.4609,,,39.589,34.8169,1.0796,19.8835
2,13/05/2024,1.6305,1.9558,5.5486,1.4757,0.9784,7.8095,,24.779,7.4608,...,4.9762,,11.7,1.4605,,,39.688,34.7702,1.0795,19.8185
3,12/05/2024,NaN,NaN,NaN,NaN,NaN,NaN,,NaN,NaN,...,NaN,,NaN,NaN,,,NaN,NaN,NaN,NaN
4,11/05/2024,NaN,NaN,NaN,NaN,NaN,NaN,,NaN,NaN,...,NaN,,NaN,NaN,,,NaN,NaN,NaN,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
9260,07/01/1999,"1,8474",,,"1,7602","1,6165",,"0,58187","34,886","7,4431",...,"1,3092","26,9876","9,18","1,9436","188,8","42,765","42,1678","0,3701","1,1632","6,8283"
9261,06/01/1999,"1,882",,,"1,7711","1,6116",,"0,582","34,85","7,4452",...,"1,3168","27,4315","9,305","1,9699","188,7","42,778","42,6949","0,3722","1,1743","6,7307"
9262,05/01/1999,"1,8944",,,"1,7965","1,6123",,"0,5823","34,917","7,4495",...,"1,3168","26,5876","9,4025","1,9655","188,775","42,848","42,5048","0,3728","1,179","6,7975"
9263,04/01/1999,"1,91",,,"1,8004","1,6168",,"0,58231","35,107","7,4501",...,"1,3111","25,2875","9,4696","1,9554","189,045","42,991","42,6799","0,3723","1,1789","6,9358"
9264,01/01/1999,,,,,,,,,,...,,,,,,,,,,

In [67]:
df = df[['date', 'USD', 'CHF', 'GBP', 'JPY', 'TRY']].copy()
df.iloc[:8508]

            date     USD     CHF      GBP     JPY      TRY
0     15/05/2024  1.0832    0.98   0.8584  168.43  34.9765
1     14/05/2024  1.0796  0.9801  0.85983  168.89  34.8169
2     13/05/2024  1.0795  0.9784  0.86023  168.25  34.7702
3     12/05/2024     NaN     NaN      NaN     NaN      NaN
4     11/05/2024     NaN     NaN      NaN     NaN      NaN
...          ...     ...     ...      ...     ...      ...
8503  02/02/2001  0,9407  1,5377   0,6364  108,43   0,6342
8504  01/02/2001  0,9406  1,5327   0,6371   108,7   0,6339
8505  31/01/2001  0,9293  1,5302   0,6367  107,87   0,6286
8506  30/01/2001  0,9197  1,5204   0,6298  107,38   0,6255
8507  29/01/2001  0,9193  1,5228   0,6304  107,15    0,625

[8508 rows x 6 columns]

In [64]:
df["USD"].apply(type).value_counts()

USD
<class 'float'>    8508
<class 'str'>       757
Name: count, dtype: int64

In [54]:
df["date"] = pd.to_datetime(df["date"], format="%d/%m/%Y")
df = df.dropna()
df

           date     USD     CHF      GBP     JPY      TRY
0    2024-05-15  1,0832    0,98   0,8584  168,43  34,9765
1    2024-05-14  1,0796  0,9801  0,85983  168,89  34,8169
2    2024-05-13  1,0795  0,9784  0,86023  168,25  34,7702
5    2024-05-10  1,0779  0,9779  0,86055  167,87  34,7431
6    2024-05-09  1,0732   0,976  0,85995  167,32  34,5811
...         ...     ...     ...      ...     ...      ...
9260 1999-01-07  1,1632  1,6165  0,70585  129,43   0,3701
9261 1999-01-06  1,1743  1,6116   0,7076  131,42   0,3722
9262 1999-01-05   1,179  1,6123   0,7122  130,96   0,3728
9263 1999-01-04  1,1789  1,6168   0,7111  133,73   0,3723
9264 1999-01-01

[6497 rows x 6 columns]

In [55]:
df = df.set_index("date").sort_index()
df

               USD     CHF      GBP     JPY      TRY
date
1999-01-01
1999-01-04  1,1789  1,6168   0,7111  133,73   0,3723
1999-01-05   1,179  1,6123   0,7122  130,96   0,3728
1999-01-06  1,1743  1,6116   0,7076  131,42   0,3722
1999-01-07  1,1632  1,6165  0,70585  129,43   0,3701
...            ...     ...      ...     ...      ...
2024-05-09  1,0732   0,976  0,85995  167,32  34,5811
2024-05-10  1,0779  0,9779  0,86055  167,87  34,7431
2024-05-13  1,0795  0,9784  0,86023  168,25  34,7702
2024-05-14  1,0796  0,9801  0,85983  168,89  34,8169
2024-05-15  1,0832    0,98   0,8584  168,43  34,9765

[6497 rows x 5 columns]

In [56]:
df.info()

<class 'pandas.core.frame.DataFrame'>
DatetimeIndex: 6497 entries, 1999-01-01 to 2024-05-15
Data columns (total 5 columns):
 #   Column  Non-Null Count  Dtype
---  ------  --------------  -----
 0   USD     6497 non-null   object
 1   CHF     6497 non-null   object
 2   GBP     6497 non-null   object
 3   JPY     6497 non-null   object
 4   TRY     6497 non-null   object
dtypes: object(5)
memory usage: 304.5+ KB

In [70]:
df = pd.read_csv("data/couverture-2g-3g-4g-en-france-par-operateur-juillet-2015.csv",
             sep=";")
df

,CODE POSTAL,CODE INSEE,NOM COMMUNE,CODE DEPARTEMENT,SURFACE COMMUNE (km²),POPULATION COMMUNE,Orange France Couverture population 4G,Bouygues Telecom Couverture population 4G,SFR Couverture population 4G,Free Mobile Couverture population 4G,...,Bouygues Telecom Couverture population 2G,SFR Couverture population 2G,Free Mobile Couverture population 2G,Par au moins un opérateur Couverture population 2G,Orange France Couverture surfacique 2G,Bouygues Telecom Couverture surfacique 2G,SFR Couverture surfacique 2G,Free Mobile Couverture surfacique 2G,Par au moins un opérateur Couverture surfacique 2G,coordonnees
0,17510,17105,CHIVES,17,20.642005,355.32,0.00,0.00,0.00,0.0,...,1.00,1.0,1.0,1.0,1.00,0.99,1.00,1.00,1.0,"45.9508835378, -0.121918052323"
1,17600,17112,LA CLISSE,17,4.896771,591.78,0.09,0.00,0.00,0.0,...,1.00,1.0,1.0,1.0,1.00,1.00,1.00,1.00,1.0,"45.7320429784, -0.75493581331"
2,17150,17116,CONSAC,17,8.915911,239.74,0.00,0.00,0.00,0.0,...,1.00,1.0,1.0,1.0,1.00,1.00,1.00,1.00,1.0,"45.4182495786, -0.588917528415"
3,17130,17118,CORIGNAC,17,10.850210,358.69,0.00,0.00,0.00,0.0,...,0.63,1.0,1.0,1.0,0.99,0.85,1.00,0.99,1.0,"45.2448604983, -0.39280322021"
4,17330,17124,COURANT,17,15.586269,371.00,0.00,0.00,0.00,0.0,...,1.00,1.0,1.0,1.0,1.00,1.00,1.00,1.00,1.0,"46.0375312829, -0.587834905531"
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
36589,70000,70378,NAVENNE,70,3.826265,1847.69,1.00,1.00,0.99,0.0,...,1.00,1.0,1.0,1.0,1.00,1.00,1.00,1.00,1.0,"47.6030208472, 6.1618556725"
36590,70000,70388,NOIDANS-LES-VESOUL,70,8.634594,2159.19,0.99,0.95,0.36,0.0,...,1.00,1.0,1.0,1.0,1.00,1.00,1.00,1.00,1.0,"47.6097514089, 6.11842989879"
36591,70100,70389,NOIRON,70,5.768295,64.01,0.00,0.00,0.00,0.0,...,1.00,1.0,1.0,1.0,1.00,0.98,0.96,1.00,1.0,"47.3828510502, 5.62597938451"
36592,70500,70399,ORMOY,70,19.577164,224.76,0.00,0.00,0.00,0.0,...,1.00,1.0,1.0,1.0,1.00,0.99,0.98,1.00,1.0,"47.8850612988, 5.99402771513"
36593,70130,70418,LE PONT-DE-PLANCHES,70,6.379713,213.99,0.00,0.00,0.00,0.0,...,1.00,1.0,1.0,1.0,1.00,0.98,0.98,1.00,1.0,"47.5374721676, 5.92263244824"

In [71]:
df.columns

Index(['CODE POSTAL', 'CODE INSEE', 'NOM COMMUNE', 'CODE DEPARTEMENT',
       'SURFACE COMMUNE (km²)', 'POPULATION COMMUNE',
       'Orange France Couverture population 4G',
       'Bouygues Telecom Couverture population 4G',
       'SFR Couverture population 4G', 'Free Mobile Couverture population 4G',
       'Par au moins un opérateur Couverture population 4G',
       'Orange France Couverture surfacique 4G',
       'Bouygues Telecom Couverture surfacique 4G',
       'SFR Couverture surfacique 4G', 'Free Mobile Couverture surfacique 4G',
       'Par au moins un opérateur Couverture surfacique 4G',
       'Orange France Couverture population 3G',
       'Bouygues Telecom Couverture population 3G',
       'SFR Couverture population 3G', 'Free Mobile Couverture population 3G',
       'Par au moins un opérateur Couverture population 3G',
       'Orange France Couverture surfacique 3G',
       'Bouygues Telecom Couverture surfacique 3G',
       'SFR Couverture surfacique 3G', 'Free Mobile Couverture surfacique 3G',
       'Par au moins un opérateur Couverture surfacique 3G',
       'Orange France Couverture population 2G',
       'Bouygues Telecom Couverture population 2G',
       'SFR Couverture population 2G', 'Free Mobile Couverture population 2G',
       'Par au moins un opérateur Couverture population 2G',
       'Orange France Couverture surfacique 2G',
       'Bouygues Telecom Couverture surfacique 2G',
       'SFR Couverture surfacique 2G', 'Free Mobile Couverture surfacique 2G',
       'Par au moins un opérateur Couverture surfacique 2G', 'coordonnees'],
      dtype='object')

In [72]:
df_long = pd.melt(df, id_vars=['CODE POSTAL', 'CODE INSEE', 'NOM COMMUNE', 'CODE DEPARTEMENT',
                     'SURFACE COMMUNE (km²)', 'POPULATION COMMUNE', 'coordonnees'])
df_long

,CODE POSTAL,CODE INSEE,NOM COMMUNE,CODE DEPARTEMENT,SURFACE COMMUNE (km²),POPULATION COMMUNE,coordonnees,variable,value
0,17510,17105,CHIVES,17,20.642005,355.32,"45.9508835378, -0.121918052323",Orange France Couverture population 4G,0.00
1,17600,17112,LA CLISSE,17,4.896771,591.78,"45.7320429784, -0.75493581331",Orange France Couverture population 4G,0.09
2,17150,17116,CONSAC,17,8.915911,239.74,"45.4182495786, -0.588917528415",Orange France Couverture population 4G,0.00
3,17130,17118,CORIGNAC,17,10.850210,358.69,"45.2448604983, -0.39280322021",Orange France Couverture population 4G,0.00
4,17330,17124,COURANT,17,15.586269,371.00,"46.0375312829, -0.587834905531",Orange France Couverture population 4G,0.00
...,...,...,...,...,...,...,...,...,...
1097815,70000,70378,NAVENNE,70,3.826265,1847.69,"47.6030208472, 6.1618556725",Par au moins un opérateur Couverture surfaciqu...,1.00
1097816,70000,70388,NOIDANS-LES-VESOUL,70,8.634594,2159.19,"47.6097514089, 6.11842989879",Par au moins un opérateur Couverture surfaciqu...,1.00
1097817,70100,70389,NOIRON,70,5.768295,64.01,"47.3828510502, 5.62597938451",Par au moins un opérateur Couverture surfaciqu...,1.00
1097818,70500,70399,ORMOY,70,19.577164,224.76,"47.8850612988, 5.99402771513",Par au moins un opérateur Couverture surfaciqu...,1.00
1097819,70130,70418,LE PONT-DE-PLANCHES,70,6.379713,213.99,"47.5374721676, 5.92263244824",Par au moins un opérateur Couverture surfaciqu...,1.00

In [78]:
df_long[["Opérateur", "Couverture", "Techno"]] = df_long["variable"].str.extract(r"(.+) (Couverture .+) (\dG)$")

In [79]:
df_long

,CODE POSTAL,CODE INSEE,NOM COMMUNE,CODE DEPARTEMENT,SURFACE COMMUNE (km²),POPULATION COMMUNE,coordonnees,variable,value,Opérateur,Couverture,Techno
0,17510,17105,CHIVES,17,20.642005,355.32,"45.9508835378, -0.121918052323",Orange France Couverture population 4G,0.00,Orange France,Couverture population,4G
1,17600,17112,LA CLISSE,17,4.896771,591.78,"45.7320429784, -0.75493581331",Orange France Couverture population 4G,0.09,Orange France,Couverture population,4G
2,17150,17116,CONSAC,17,8.915911,239.74,"45.4182495786, -0.588917528415",Orange France Couverture population 4G,0.00,Orange France,Couverture population,4G
3,17130,17118,CORIGNAC,17,10.850210,358.69,"45.2448604983, -0.39280322021",Orange France Couverture population 4G,0.00,Orange France,Couverture population,4G
4,17330,17124,COURANT,17,15.586269,371.00,"46.0375312829, -0.587834905531",Orange France Couverture population 4G,0.00,Orange France,Couverture population,4G
...,...,...,...,...,...,...,...,...,...,...,...,...
1097815,70000,70378,NAVENNE,70,3.826265,1847.69,"47.6030208472, 6.1618556725",Par au moins un opérateur Couverture surfaciqu...,1.00,Par au moins un opérateur,Couverture surfacique,2G
1097816,70000,70388,NOIDANS-LES-VESOUL,70,8.634594,2159.19,"47.6097514089, 6.11842989879",Par au moins un opérateur Couverture surfaciqu...,1.00,Par au moins un opérateur,Couverture surfacique,2G
1097817,70100,70389,NOIRON,70,5.768295,64.01,"47.3828510502, 5.62597938451",Par au moins un opérateur Couverture surfaciqu...,1.00,Par au moins un opérateur,Couverture surfacique,2G
1097818,70500,70399,ORMOY,70,19.577164,224.76,"47.8850612988, 5.99402771513",Par au moins un opérateur Couverture surfaciqu...,1.00,Par au moins un opérateur,Couverture surfacique,2G
1097819,70130,70418,LE PONT-DE-PLANCHES,70,6.379713,213.99,"47.5374721676, 5.92263244824",Par au moins un opérateur Couverture surfaciqu...,1.00,Par au moins un opérateur,Couverture surfacique,2G

In [80]:
geo = (pd.read_csv("data/correspondance-code-insee-code-postal.csv",
                 sep=";",
                 usecols=range(11)
                )
     )
geo

,Code INSEE,Code Postal,Commune,Département,Région,Statut,Altitude Moyenne,Superficie,Population,geo_point_2d,geo_shape
0,31080,31350,BOULOGNE-SUR-GESSE,HAUTE-GARONNE,MIDI-PYRENEES,Chef-lieu canton,301.0,2470.0,1.6,"43.2904403081, 0.650641474176","{""type"": ""Polygon"", ""coordinates"": [[[0.671852..."
1,11143,11510,FEUILLA,AUDE,LANGUEDOC-ROUSSILLON,Commune simple,314.0,2426.0,0.1,"42.9291375888, 2.90138923544","{""type"": ""Polygon"", ""coordinates"": [[[2.906996..."
2,43028,43200,BESSAMOREL,HAUTE-LOIRE,AUVERGNE,Commune simple,888.0,743.0,0.4,"45.1306448726, 4.07952494849","{""type"": ""Polygon"", ""coordinates"": [[[4.091674..."
3,78506,78660,PRUNAY-EN-YVELINES,YVELINES,ILE-DE-FRANCE,Commune simple,155.0,2717.0,0.8,"48.5267627187, 1.80513972814","{""type"": ""Polygon"", ""coordinates"": [[[1.829610..."
4,84081,84310,MORIERES-LES-AVIGNON,VAUCLUSE,PROVENCE-ALPES-COTE D'AZUR,Commune simple,49.0,1042.0,7.6,"43.9337788848, 4.90875878315","{""type"": ""Polygon"", ""coordinates"": [[[4.927176..."
...,...,...,...,...,...,...,...,...,...,...,...
36737,74066,74270,CHAVANNAZ,HAUTE-SAVOIE,RHONE-ALPES,Commune simple,564.0,321.0,0.2,"46.0500384099, 6.01652644319","{""type"": ""Polygon"", ""coordinates"": [[[6.026228..."
36738,67315,67630,NEEWILLER-PRES-LAUTERBOURG,BAS-RHIN,ALSACE,Commune simple,157.0,725.0,0.7,"48.9516989257, 8.11931601006","{""type"": ""Polygon"", ""coordinates"": [[[8.106826..."
36739,07122,07200,LACHAPELLE-SOUS-AUBENAS,ARDECHE,RHONE-ALPES,Commune simple,257.0,1018.0,1.5,"44.5622616562, 4.35906947518","{""type"": ""Polygon"", ""coordinates"": [[[4.356584..."
36740,01026,01380,BAGE-LE-CHATEL,AIN,RHONE-ALPES,Chef-lieu canton,202.0,86.0,0.8,"46.3077069231, 4.92862084189","{""type"": ""Polygon"", ""coordinates"": [[[4.926593..."
36741,50224,50160,GUILBERVILLE,MANCHE,BASSE-NORMANDIE,Commune simple,165.0,2224.0,1.0,"48.9866701737, -0.949588175705","{""type"": ""Polygon"", ""coordinates"": [[[-0.99753..."

In [90]:
statut = pd.CategoricalDtype(categories=['Commune simple', 'Chef-lieu canton', 'Sous-préfecture',
                                         'Préfecture', 'Préfecture de région', "Capitale d'état"],
                             ordered=True)

df_all = pd.merge(df_long, geo, left_on="CODE INSEE", right_on="Code INSEE", how="left")
df_all["Statut"] = df_all["Statut"].astype(statut)
df_all

,CODE POSTAL,CODE INSEE,NOM COMMUNE,CODE DEPARTEMENT,SURFACE COMMUNE (km²),POPULATION COMMUNE,coordonnees,variable,value,Opérateur,...,Code Postal,Commune,Département,Région,Statut,Altitude Moyenne,Superficie,Population,geo_point_2d,geo_shape
0,17510,17105,CHIVES,17,20.642005,355.32,"45.9508835378, -0.121918052323",Orange France Couverture population 4G,0.00,Orange France,...,17510,CHIVES,CHARENTE-MARITIME,POITOU-CHARENTES,Commune simple,108.0,2062.0,0.4,"45.9508835378, -0.121918052323","{""type"": ""Polygon"", ""coordinates"": [[[-0.10484..."
1,17600,17112,LA CLISSE,17,4.896771,591.78,"45.7320429784, -0.75493581331",Orange France Couverture population 4G,0.09,Orange France,...,17600,LA CLISSE,CHARENTE-MARITIME,POITOU-CHARENTES,Commune simple,34.0,524.0,0.6,"45.7320429784, -0.75493581331","{""type"": ""Polygon"", ""coordinates"": [[[-0.74528..."
2,17150,17116,CONSAC,17,8.915911,239.74,"45.4182495786, -0.588917528415",Orange France Couverture population 4G,0.00,Orange France,...,17150,CONSAC,CHARENTE-MARITIME,POITOU-CHARENTES,Commune simple,58.0,905.0,0.2,"45.4182495786, -0.588917528415","{""type"": ""Polygon"", ""coordinates"": [[[-0.60200..."
3,17130,17118,CORIGNAC,17,10.850210,358.69,"45.2448604983, -0.39280322021",Orange France Couverture population 4G,0.00,Orange France,...,17130,CORIGNAC,CHARENTE-MARITIME,POITOU-CHARENTES,Commune simple,69.0,1112.0,0.3,"45.2448604983, -0.39280322021","{""type"": ""Polygon"", ""coordinates"": [[[-0.41318..."
4,17330,17124,COURANT,17,15.586269,371.00,"46.0375312829, -0.587834905531",Orange France Couverture population 4G,0.00,Orange France,...,17330,COURANT,CHARENTE-MARITIME,POITOU-CHARENTES,Commune simple,55.0,1574.0,0.4,"46.0375312829, -0.587834905531","{""type"": ""Polygon"", ""coordinates"": [[[-0.58528..."
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
1097815,70000,70378,NAVENNE,70,3.826265,1847.69,"47.6030208472, 6.1618556725",Par au moins un opérateur Couverture surfaciqu...,1.00,Par au moins un opérateur,...,70000,NAVENNE,HAUTE-SAONE,FRANCHE-COMTE,Commune simple,321.0,400.0,1.8,"47.6030208472, 6.1618556725","{""type"": ""Polygon"", ""coordinates"": [[[6.157643..."
1097816,70000,70388,NOIDANS-LES-VESOUL,70,8.634594,2159.19,"47.6097514089, 6.11842989879",Par au moins un opérateur Couverture surfaciqu...,1.00,Par au moins un opérateur,...,70000,NOIDANS-LES-VESOUL,HAUTE-SAONE,FRANCHE-COMTE,Commune simple,306.0,856.0,2.1,"47.6097514089, 6.11842989879","{""type"": ""Polygon"", ""coordinates"": [[[6.119037..."
1097817,70100,70389,NOIRON,70,5.768295,64.01,"47.3828510502, 5.62597938451",Par au moins un opérateur Couverture surfaciqu...,1.00,Par au moins un opérateur,...,70100,NOIRON,HAUTE-SAONE,FRANCHE-COMTE,Commune simple,219.0,575.0,0.1,"47.3828510502, 5.62597938451","{""type"": ""Polygon"", ""coordinates"": [[[5.640740..."
1097818,70500,70399,ORMOY,70,19.577164,224.76,"47.8850612988, 5.99402771513",Par au moins un opérateur Couverture surfaciqu...,1.00,Par au moins un opérateur,...,70500,ORMOY,HAUTE-SAONE,FRANCHE-COMTE,Commune simple,267.0,1962.0,0.2,"47.8850612988, 5.99402771513","{""type"": ""Polygon"", ""coordinates"": [[[5.945622..."
1097819,70130,70418,LE PONT-DE-PLANCHES,70,6.379713,213.99,"47.5374721676, 5.92263244824",Par au moins un opérateur Couverture surfaciqu...,1.00,Par au moins un opérateur,...,70130,LE PONT-DE-PLANCHES,HAUTE-SAONE,FRANCHE-COMTE,Commune simple,234.0,690.0,0.2,"47.5374721676, 5.92263244824","{""type"": ""Polygon"", ""coordinates"": [[[5.938235..."

In [86]:
df_all["Statut"].unique()

array(['Commune simple', 'Chef-lieu canton', 'Sous-préfecture',
       'Préfecture', 'Préfecture de région', "Capitale d'état"],
      dtype=object)

In [91]:
(df_all
 .loc[(df_all["Couverture"]=="Couverture surfacique") & (df_all["Techno"]=="4G")]
 .groupby("Statut")["value"]
 .mean()
)

/tmp/ipykernel_8727/1321047617.py:3: FutureWarning: The default of observed=False is deprecated and will be changed to True in a future version of pandas. Pass observed=False to retain current behavior or observed=True to adopt the future default and silence this warning.
  .groupby("Statut")["value"]

Statut
Commune simple          0.201893
Chef-lieu canton        0.302156
Sous-préfecture         0.449766
Préfecture              0.724730
Préfecture de région    0.893238
Capitale d'état         0.996000
Name: value, dtype: float64

In [93]:
(df_all
 .loc[(df_all["Couverture"]=="Couverture surfacique") & (df_all["Techno"]=="4G")]
 .groupby("Opérateur")["value"]
 .mean()
 .sort_values()
)

Opérateur
Free Mobile                  0.033767
SFR                          0.156458
Orange France                0.256066
Bouygues Telecom             0.256999
Par au moins un opérateur    0.360874
Name: value, dtype: float64

In [95]:
(df_all
 .loc[(df_all["Couverture"]=="Couverture surfacique") & (df_all["Techno"]=="4G")]
 .groupby(["Statut", "Opérateur"])["value"]
 .mean()
 .idxmin()
)

/tmp/ipykernel_8727/261650443.py:3: FutureWarning: The default of observed=False is deprecated and will be changed to True in a future version of pandas. Pass observed=False to retain current behavior or observed=True to adopt the future default and silence this warning.
  .groupby(["Statut", "Opérateur"])["value"]

('Commune simple', 'Free Mobile')